[Disable AV] Adding More AV Vendors' Instructions
citizenfx/fivem-docs pull request #226
Opened 2021-01-08 13:57 UTC by mcastiglia

Adding more AV vendor links (known that McAfee and Bitdefender block FiveM by default from myself and my friends. Assuming the same with Kaspersky because they take the same aggressive approach as Bitdefender.)
For Kaspersky, that was the best link I could find although it is in a page with other content as well.

2021-01-08 16:30 UTC, mcastiglia commented
I have since added Newegg as a retailer for GTA V (more options is never a bad thing and Newegg is pretty popular), and removed Windows 7 and 8.1 from the supported OSs on System Requirements.

2021-01-08 18:55 UTC, AvarianKnight commented on content/docs/client-manual/system-requirements.md
> +FiveM requires a _fully_ updated version of Windows 10. An outdated operating system may not
Doesn't the game still work on Win 7 and Win 8.1?

2021-01-08 19:25 UTC, mcastiglia commented on content/docs/client-manual/system-requirements.md
> +FiveM requires a _fully_ updated version of Windows 10. An outdated operating system may not
Yes, but as stated in the commit description, if it's there people will think that it's an officially supported configuration, which it is not (because they both reached EOL) (Supporting this: https://discord.com/channels/192358910387159041/455024366091108352/792340416342130688 https://discord.com/channels/192358910387159041/455024366091108352/795128987654422528)

2021-01-08 22:59 UTC, lze3 commented on content/docs/client-manual/system-requirements.md
> +FiveM requires a _fully_ updated version of Windows 10. An outdated operating system may not
> Yes, but as stated in the commit description, if it's there people will think that it's an officially supported configuration, which it is not (because they both reached EOL) (Supporting this: https://discord.com/channels/192358910387159041/455024366091108352/792340416342130688 https://discord.com/channels/192358910387159041/455024366091108352/795128987654422528)
> If you would like me to revert that though, I can do that.

According to [fivem.net](https://fivem.net), System Requirements state that the system must be running Windows 8.1 or Windows 10. I think it's best to keep it as for consistency purposes:
```suggestion
FiveM requires a _fully_ updated version of Windows 8.1 or Windows 10. An outdated operating system may not
```

2021-01-08 23:06 UTC, mcastiglia commented
Ok, it's now changed to be 8.1 or 10

2021-01-08 23:08 UTC, lze3 approved these changes

2021-01-30 22:34 UTC, technetium-cfx requested changes

2021-01-30 22:34 UTC, technetium-cfx commented on content/docs/client-manual/disabling-antivirus.md
> +    - [Kaspersky](https://usa.kaspersky.com/blog/kaspersky-add-exclusion/11075/#:~:text=How%20to%20add%20an%20application%20to%20exclusions%20in%20Kaspersky%20Internet%20Security)
These URLs are unnecessarily long. Could you reduce them to the minimum?

2021-02-03 12:52 UTC, mcastiglia commented
They are now as short as possible while still working.

2021-02-03 14:34 UTC, technetium-cfx commented
Would probably like a non-blog item for Kaspersky, but this appears to be accurate enough. Looks good!

2021-02-03 14:34 UTC, merged