Update creating-your-first-script-csharp.md
citizenfx/fivem-docs pull request #227
Opened 2021-01-09 23:21 UTC by SaSiNO97

Changed the complicated `RegisterCommand` with the more readable, newbie-friendly, and overall better `CommandAttribute`.
I tested the new code, it compiles and it works as intended.

2021-01-11 01:16 UTC, jaymo1011 commented
Why is the `OnClientResourceStart` event handler still registered manually instead of using `EventHandlerAttribute` or even in the code in the first place when it isn't used by the car spawner logic?

2021-01-11 01:26 UTC, jaymo1011 commented on content/docs/scripting-manual/introduction/creating-your-first-script-csharp.md
> +        [Command("car")]
Though not required, it might be a good idea to explicitly add the `Restricted = false` on the attribute to give a hint on how one would restrict usage of the command using the attribute context.

2021-01-11 01:28 UTC, jaymo1011 commented on content/docs/scripting-manual/introduction/creating-your-first-script-csharp.md
> +        args = new[] { "[CarSpawner]", $"I wish I could spawn this {(args.Count() > 0 ? $"{args[0]} or" : "")} adder but my owner was too lazy. :(" }
Wouldn't `args.Length` work here without the need of LINQ?

2021-01-14 04:06 UTC, SaSiNO97 commented
> Why is the `OnClientResourceStart` event handler still registered manually instead of using `EventHandlerAttribute` or even in the code in the first place when it isn't used by the car spawner logic? It'd make more sense to have it be removed entirely in the context of a newbie friendly guide :)

Wait what :/ Because I didn't even know a `EventHandlerAttribute` even existed... This shows how seriously we need an updated documentation.

2021-01-14 04:07 UTC, SaSiNO97 commented on content/docs/scripting-manual/introduction/creating-your-first-script-csharp.md
> +        args = new[] { "[CarSpawner]", $"I wish I could spawn this {(args.Count() > 0 ? $"{args[0]} or" : "")} adder but my owner was too lazy. :(" }
Yeah true. I personally use LINQ a lot, that's why I used it there, however, it's just a personal preference and `string.Length` may be faster.

2021-01-17 15:45 UTC, lze3 requested changes

2021-01-17 15:45 UTC, lze3 commented on content/docs/scripting-manual/introduction/creating-your-first-script-csharp.md
> +An important thing to notice is that the `CreateVehicle` method is [asnychronous](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/); this means that the wrapping metho
Typo

```suggestion
An important thing to notice is that the `CreateVehicle` method is [asynchronous](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/); this means that the wrapping method, in our case `CarCommand` must be `async` too, since we want to wait for our vehicle to be created before proceeding.
```

2021-01-22 22:15 UTC, closed without merging