Added keymaster link and reworded the sentence
citizenfx/fivem-docs pull request #316
Opened 2022-03-25 07:36 UTC by duckhunter392

The previous step assumed that the person already made a key, but the steps don't say how to make a key. This change tells them to go to the keymaster (and provides a link to it).

2022-04-01 08:48 UTC, blattersturm requested changes

2022-04-01 08:48 UTC, blattersturm commented on content/docs/server-manual/setting-up-a-server-txadmin.md
> +12. Create a key in the [Keymaster](https://keymaster.fivem.net), enter it here in the 'Before you begin' step, and click 'Run Recipe'.<br>
> enter it here in the 'Before you begin' step

Huh?

2022-04-06 21:24 UTC, duckhunter392 commented on content/docs/server-manual/setting-up-a-server-txadmin.md
> +12. Create a key in the [Keymaster](https://keymaster.fivem.net), enter it here in the 'Before you begin' step, and click 'Run Recipe'.<br>
Adjusted it to be a bit more clear. I tried to leave the original wording there as best as possible, while being more clear in terms of where to create a key.

2024-08-07 20:14 UTC, AvarianKnight commented
This change set is old, if you're interesting in continuing your PR please rebase to the latest commit.

2024-08-07 20:14 UTC, closed without merging