Create entries for request control filter modes
citizenfx/fivem-docs pull request #318
Opened 2022-04-04 17:32 UTC by 4mmonium

This PR adds documentation for the following console variables:

- sv_filterRequestControl
- sv_filterRequestControlSettleTimer

2022-04-06 06:29 UTC, blattersturm requested changes

2022-04-06 06:29 UTC, blattersturm commented on content/docs/server-manual/server-commands.md
> +- -1: Default, equivalent to 2 at this time, but will also warn in console so users can fix stuff/be told to disable it.
'so users can fix stuff/be told to disable it' -> don't copy that raw line :-)

2022-04-06 06:29 UTC, blattersturm commented on content/docs/server-manual/server-commands.md
> +- Control request events can't be routed across routing buckets. This likely wasn't a thing anyway, but just a double-check.
Same for the 'This likely wasn't a thing anyway' bit.

2022-04-06 06:29 UTC, blattersturm commented on content/docs/server-manual/server-commands.md
> +A console variable that allows you to set after how long (based on entity creation time) an entity should be blocked from a `REQUEST_CONTROL_EVENT`. This will only apply to filter request control mod
\+ `in milliseconds`

2022-04-06 12:28 UTC, 4mmonium commented on content/docs/server-manual/server-commands.md
> +- -1: Default, equivalent to 2 at this time, but will also warn in console so users can fix stuff/be told to disable it.
Ah, funny how I missed that even though I proof read it twice 😅
Anyway, left as _-1: Default, equivalent to 2 at this time, but will also warn in console_. I ideally was going to add a 'for debug purposes in there' after 'warn in console', but I didn't know if it fitted that criteria.

2022-04-06 12:30 UTC, 4mmonium commented on content/docs/server-manual/server-commands.md
> +- Control request events can't be routed across routing buckets. This likely wasn't a thing anyway, but just a double-check.
Yep, removed!

2022-04-06 12:33 UTC, 4mmonium commented on content/docs/server-manual/server-commands.md
> +A console variable that allows you to set after how long (based on entity creation time) an entity should be blocked from a `REQUEST_CONTROL_EVENT`. This will only apply to filter request control mod
Changed to: https://github.com/citizenfx/fivem-docs/pull/318/files#diff-331e99259d1395f290e695c1c52cfb483254b82a1a1534aadcaabc08ad0d8e5dR249

Sorry, squashed the commits and force pushed to have everything as one commit, I probably should have done that after this commit so diffs are easier to read, my bad.

2022-04-10 07:02 UTC, blattersturm approved these changes
OK. Can someone still write a draft for the change notification? I'll probably merge the changes *after* next recommended bump.

2022-05-30 09:13 UTC, merged