feat: JS examples & more
citizenfx/fivem-docs pull request #382
Opened 2023-04-15 10:53 UTC by JajarGaming

2024-01-27 09:07 UTC, PsychoShock requested changes

2024-01-27 09:07 UTC, PsychoShock commented on content/docs/client-manual/where-to-buy-gtav.md
> +- [Rockstar Warehouse](https://store.rockstargames.com/en/game/buy-gta-v)
This should be replace with `https://store.rockstargames.com/game/buy-gta-v`.

2024-04-27 05:24 UTC, PsychoShock requested changes
Hello,

Nice work. I have left some comments that can be change __in my opinion__.

Thanks :)

2024-04-27 05:24 UTC, PsychoShock commented on content/docs/developers/compiling-fivem.md
> +**Known issues**
Instead of `Know issue`, I think it would be better for docs for `Error that can occur`

2024-04-27 05:24 UTC, PsychoShock commented on content/docs/game-references/game-events.md
> +| Event name                                         |
Not sure about this, no idea what @4mmonium think but __in my opinion__ I would rather have `description` empty but one day someone updating them instead of removing them.

2024-08-07 20:24 UTC, AvarianKnight commented
This commit has too many different changes across too many files. If you're going to do changes please separate your changes into multiple PRs.

2024-08-07 20:24 UTC, closed without merging