Add builds: 2824 to 2944
citizenfx/fivem-docs pull request #390
Opened 2023-06-22 16:03 UTC by 4mmonium

Adds missing builds from 2824 to 2944.
Gathered from: https://rage.re/t/draft-pc-game-builds/68

2023-06-24 19:37 UTC, blattersturm requested changes

2023-06-24 19:37 UTC, blattersturm commented on content/docs/server-manual/server-commands.md
> +| 2845   | -                                    | -                           |
2824/2845 aren't actually supported by the game, and these docs are meant for end users, not as a general reference.

2023-06-24 21:04 UTC, 4mmonium commented on content/docs/server-manual/server-commands.md
> +| 2845   | -                                    | -                           |
Ah, my bad, I think I should have looked [here](https://github.com/citizenfx/fivem/blob/a01741758e2fac4cbd11d704b1490fadc83f4a7c/code/client/shared/CrossBuildRuntime.h#L8)

I looked at the wrong places [(1)](https://github.com/citizenfx/fivem/blob/a01741758e2fac4cbd11d704b1490fadc83f4a7c/code/components/gta-core-five/include/netPeerAddress.h#L142) [(2)](https://github.com/citizenfx/fivem/blob/a01741758e2fac4cbd11d704b1490fadc83f4a7c/code/components/gta-net-five/src/NetHook.cpp#L1713).

Will correct and commit again.

2023-06-24 21:11 UTC, 4mmonium commented on content/docs/server-manual/server-commands.md
> +| 2845   | -                                    | -                           |
All done now.
Here's the corrected [commit](https://github.com/citizenfx/fivem-docs/pull/390/files#diff-331e99259d1395f290e695c1c52cfb483254b82a1a1534aadcaabc08ad0d8e5dR173)

2023-06-29 07:12 UTC, Disquse commented on content/docs/server-manual/server-commands.md
> +| 2944   | mp2023_01, mp2023_01_g9ec            | San Andreas Mercenaries     |
I don't think including `mp2023_01_g9ec`is necessary, these are stub DLCs (disabled from loading in FiveM). We never included these in docs for older DLCs before😄

2023-06-29 07:22 UTC, 4mmonium commented on content/docs/server-manual/server-commands.md
> +| 2944   | mp2023_01, mp2023_01_g9ec            | San Andreas Mercenaries     |
> I don't think including `mp2023_01_g9ec`is necessary, these are stub DLCs (disabled from loading in FiveM). We never included these in docs for older DLCs before😄

Removed stub DLC 😃

2023-06-30 23:29 UTC, merged