Add playerEnteredScope/playerLeftScope examples
citizenfx/fivem-docs pull request #413
Opened 2024-01-29 14:55 UTC by 4mmonium

Adds the implementation examples to the OneSync guide.

2024-01-29 20:26 UTC, AvarianKnight commented
These events notoriously are bad to use (bad performance), is it a good idea to publicly document them?

2024-01-30 15:08 UTC, 4mmonium commented
> These events notoriously are bad to use (bad performance), is it a good idea to publicly document them?

You make a good point, although I think that depends on how the end user writes their implementation. If they write a for loop inside the handler to keep track of users, it's going to be non-performant, if they just use it to assign player related variables i.e. `playerData[playerId].something = true` it may be ok.

Perhaps a word of caution should be added, stating that the method shouldn't be used to perform CPU-intensive operations (such as a for-loop) inside the handler(s) as it will lead to bad performance, for the simple fact that the handler will be triggered every time someone enters/leaves the scope.

Nice catch! 😊

2024-02-29 22:26 UTC, AvarianKnight commented
I don't think the issue here is user implementation but the overhead of events, for larger servers using these no matter the circumstance can lead to weird performance issues.

Players should mostly be using state bags if they want to do stuff when a player enters another players scope.

2024-08-15 15:46 UTC, AvarianKnight requested changes

2024-08-15 15:46 UTC, AvarianKnight commented on content/docs/scripting-reference/onesync/_index.md
> +```
````suggestion

```
````

2024-08-15 15:46 UTC, AvarianKnight commented on content/docs/scripting-reference/onesync/_index.md
> +This event handler is triggered when a player enters another player's scope.
```suggestion
{{% alert theme="warning" %}}
Using these events is frowned upon, these events have scaling performance costs. For every person within the scope of the player on every enter/leave scope this this will be called an additional time, so having 32 players within the scope of a player will lead to this being called 32 times. Whenever possible you should use state bags if you need to trigger scoped events.
{{% /alert %}}

This event handler is triggered when a player enters another player's scope.
```

2024-08-15 15:46 UTC, AvarianKnight commented on content/docs/scripting-reference/onesync/_index.md
> +This event handler is triggered when a player leaves another player's scope.
```suggestion
{{% alert theme="warning" %}}
Using these events is frowned upon, these events have scaling performance costs. For every person within the scope of the player on every enter/leave scope this this will be called an additional time, so having 32 players within the scope of a player will lead to this being called 32 times. Whenever possible you should use state bags if you need to trigger scoped events.
{{% /alert %}}

This event handler is triggered when a player leaves another player's scope.
```

2024-08-15 16:06 UTC, AvarianKnight requested changes
I used the wrong formatting here

2024-08-15 16:06 UTC, AvarianKnight commented on content/docs/scripting-reference/onesync/_index.md
> +{{% alert theme="warning" %}}
```suggestion
{{% alert title="Performance Warning" color="warning" %}}
```

2024-08-15 16:06 UTC, AvarianKnight commented on content/docs/scripting-reference/onesync/_index.md
> +{{% alert theme="warning" %}}
```suggestion
{{% alert title="Performance Warning" color="warning" %}}
```

2024-08-15 16:50 UTC, merged