Add License Types & Providers
citizenfx/fivem-docs pull request #416
Opened 2024-02-26 21:00 UTC by TheGamerzs

These are the only license providers that I have seen.
`license2` may need to be verified to see how it's "activated". (i.e. switching SocialClub accounts or just having SocialClub multiple accounts present)

2024-04-27 04:24 UTC, PsychoShock requested changes
Hello,

I have left some comments if you wanna check them out. This is my personnal opinion for this PR.

Nice work! :)

2024-04-27 04:24 UTC, PsychoShock commented on content/docs/scripting-reference/runtimes/lua/functions/GetPlayerIdentifiers.md
> +Check for commonly used identifiers with this method;  works well when triggered by the `playerConnecting` event.
This can be removed in my opinion.

2024-04-27 04:24 UTC, PsychoShock commented on content/docs/scripting-reference/runtimes/lua/functions/GetPlayerIdentifiers.md
> +|`ip`|IP Adress|IPv4|string|
This will not work correctly. It's because you did `|Value|` instead of `| Value |` so it won't parse correctly. :)

In Markdown, the standard format for a table header is with spaces surrounding the text to separate the pipes

2024-08-11 04:34 UTC, AvarianKnight commented
This is awaiting validation, as I'm not sure when `license2` is used and I want to be completely sure before adding this to the docs.

2024-08-11 15:21 UTC, AvarianKnight requested changes

2024-08-11 15:21 UTC, AvarianKnight commented on content/docs/scripting-reference/runtimes/lua/functions/GetPlayerIdentifiers.md
> +| `fivem`    | CFX.re                   | User Id                                                                   | int       |
```suggestion
| `fivem`    | Cfx.re                   | User Id                                                                   | int       |
```

2024-08-11 15:21 UTC, AvarianKnight commented on content/docs/scripting-reference/runtimes/lua/functions/GetPlayerIdentifiers.md
> +** `license2` - This can be the same value as `license`
```suggestion
* `license2` - This identifier is the ROS license for people who use steam, this identifier can be the same value as `license`
```

2024-08-12 19:52 UTC, merged