refactor(page/framework): new descriptions and frameworks
citizenfx/fivem-docs pull request #420
Opened 2024-04-27 05:08 UTC by PsychoShock

- This have better descriptions
- Added a section if user need help (what to do)
- Added two new framework to the list (popular)
 - Qbox
 - ND

2024-04-27 05:09 UTC, PsychoShock commented
This will include https://github.com/citizenfx/fivem-docs/pull/414

2024-08-07 20:38 UTC, AvarianKnight requested changes
Thank you for the PR!

Here's some initial thoughts

2024-08-07 20:38 UTC, AvarianKnight commented on content/docs/server-manual/frameworks.md
> +**Note:** Any suggested framework must be readily available for use upon request.
```suggestion

```
This line isn't necessary,

2024-08-07 20:38 UTC, AvarianKnight commented on content/docs/server-manual/frameworks.md
> +- [ESX](https://github.com/esx-framework/esx-legacy) ([FiveM documentation](https://documentation.esx-framework.org/legacy/installation))
```suggestion
- [ESX](https://github.com/esx-framework/esx-legacy) ([Docs](https://documentation.esx-framework.org/legacy/installation))
```

We should keep these as just `Docs`

2024-08-07 20:38 UTC, AvarianKnight commented on content/docs/server-manual/frameworks.md
> +- [ND](https://github.com/ND-Framework/ND_Core) ([FiveM documentation](https://ndcore.dev/setup))
```suggestion
- [ND](https://github.com/ND-Framework/ND_Core) ([Docs](https://ndcore.dev/setup))
```

2024-08-07 20:38 UTC, AvarianKnight commented on content/docs/server-manual/frameworks.md
> +- [QBCore](https://github.com/qbcore-framework/qb-core) ([FiveM documentation](https://docs.qbcore.org/qbcore-documentation/))
```suggestion
- [QBCore](https://github.com/qbcore-framework/qb-core) ([Docs](https://docs.qbcore.org/qbcore-documentation/))
```

2024-08-07 20:38 UTC, AvarianKnight commented on content/docs/server-manual/frameworks.md
> +- [vRP](https://github.com/vRP-framework/vRP) ([FiveM documentation](https://vrp-framework.github.io/vRP/))
Why did you remove VORP?

2024-08-07 20:38 UTC, AvarianKnight commented on content/docs/server-manual/frameworks.md
> +- [Qbox](https://github.com/Qbox-project/qbx_core) ([FiveM documentation](https://docs.qbox.re/installation))
```suggestion
- [Qbox](https://github.com/Qbox-project/qbx_core) ([Docs](https://docs.qbox.re/installation))
```

2024-08-07 20:38 UTC, AvarianKnight commented on content/docs/server-manual/frameworks.md
> +- [vRP](https://github.com/vRP-framework/vRP) ([FiveM documentation](https://vrp-framework.github.io/vRP/))
```suggestion
- [vRP](https://github.com/vRP-framework/vRP) ([Docs](https://vrp-framework.github.io/vRP/))
```

2024-08-08 06:43 UTC, PsychoShock commented on content/docs/server-manual/frameworks.md
> +- [vRP](https://github.com/vRP-framework/vRP) ([FiveM documentation](https://vrp-framework.github.io/vRP/))
Isn't the page __only__ for FiveM? Old description was:
> Finding a Framework for your FiveM server.

So having a RedM framework will also mean to change the "FiveM" only to CFX platforms.

2024-08-08 21:38 UTC, AvarianKnight commented on content/docs/server-manual/frameworks.md
> +- [vRP](https://github.com/vRP-framework/vRP) ([FiveM documentation](https://vrp-framework.github.io/vRP/))
Considering the state of RedM docs (or the lack thereof), this should just be kept as-is, in the future it can be removed if we end up adding RedM specific documentation.

2024-08-08 21:40 UTC, PsychoShock commented on content/docs/server-manual/frameworks.md
> +- [vRP](https://github.com/vRP-framework/vRP) ([FiveM documentation](https://vrp-framework.github.io/vRP/))
So I keep the "FiveM" only part and re-add voRP?

2024-08-08 23:56 UTC, AvarianKnight commented on content/docs/server-manual/frameworks.md
> +- [vRP](https://github.com/vRP-framework/vRP) ([FiveM documentation](https://vrp-framework.github.io/vRP/))
I would just add it back how it was 
```
- [VORP](https://github.com/VORPCORE/vorp-core-lua) ([Docs](https://vorpcore.github.io/VORP_Documentation)) (RedM)
```
or
```
- [VORP for RedM](https://github.com/VORPCORE/vorp-core-lua) ([Docs](https://vorpcore.github.io/VORP_Documentation))
```

2024-08-12 19:52 UTC, merged