feat(native/doc): first understanding
citizenfx/fivem-docs pull request #430
Opened 2024-06-04 19:11 UTC by PsychoShock

This should make users know what are natives (basic understanding)

2024-06-05 04:24 UTC, AvarianKnight commented on content/docs/scripting-manual/introduction/about-native-functions.md
> +- **FiveM Community Forums**: The [FiveM forums](https://forum.fivem.net/) are another valuable resource. Here, you can find discussions, tutorials, and examples from other developers who share their
This should be just `Community Forums` and `[Cfx.re Forums](https://forum.cfx.re/)`

2024-06-05 04:24 UTC, AvarianKnight commented on content/docs/scripting-manual/introduction/about-native-functions.md
> +title: Understanding and Using Native Functions in FiveM
This document shouldn't be game specific they work the same across different games (GTA5, RDR2, GTA4)

Maybe something like `Understanding and Using Natives on supported platforms`

2024-06-05 04:24 UTC, AvarianKnight commented on content/docs/scripting-manual/introduction/about-native-functions.md
> +In FiveM, you have access to what are called "native functions" or simply "natives". These functions interact with the game directly, allowing you to perform a wide variety of actions within the game
Same note as above

Rewording could be:
`In the games supported by the platform,`

2024-06-05 04:24 UTC, AvarianKnight commented on content/docs/scripting-manual/introduction/about-native-functions.md
> +FiveM provides comprehensive documentation for native functions, which can be found on our official website. This documentation is essential for understanding what each native function does, how to u
`FiveM` -> `Cfx`

2024-06-05 04:24 UTC, AvarianKnight commented on content/docs/scripting-manual/introduction/about-native-functions.md
> +- **FiveM Native Reference**: The primary resource for native functions is the [FiveM Native Reference](https://docs.fivem.net/natives/). This reference includes a searchable database of all availabl
Might want to include RedM native references too even if they're unofficial 

https://redm.disquse.me/natives/

2024-06-05 04:24 UTC, AvarianKnight commented on content/docs/scripting-manual/introduction/about-native-functions.md
> +### Client Natives
It might be worth noting here `Cfx Natives` as they are used when a resource uses `game "common"`

2024-06-05 04:24 UTC, AvarianKnight commented on content/docs/scripting-reference/runtimes/lua/functions/Citizen.InvokeNative.md
> +`Citizen.InvokeNative` is typically used when you need to access functionality that is not available through Lua scripting alone. This could include advanced game mechanics, low-level engine features
This seems redundant

2024-06-05 04:24 UTC, AvarianKnight commented on content/docs/scripting-reference/runtimes/lua/functions/Citizen.InvokeNative.md
> +
Might want to go in depth with how to get return data with natives.

2024-06-05 04:24 UTC, AvarianKnight commented on content/docs/scripting-reference/runtimes/lua/functions/Citizen.InvokeNative.md
> +**Note:** `Citizen.InvokeNative` should primarily be used for either undocumented natives or natives with incorrect parameters defined. For documented natives, using the direct method is recommended.
This should probably also state taht it should be used for natives that need to handle structs or buffers

2024-06-05 04:24 UTC, AvarianKnight commented on content/docs/scripting-reference/runtimes/lua/functions/Citizen.InvokeNative.md
> +Citizen.InvokeNative(0xDCBA2512, "MY_CUSTOM_ENTRY", "Hello, FiveM!")
It would probably be better to use a game native instead of a Cfx native here

```
local DOES_ENTITY_EXIST = 0x7239B21A38F536BA
Citizen.InvokeNative(DOES_ENTITY_EXIST, entityId, Citizen.ReturnResultAnyway())
```

2024-06-05 04:24 UTC, AvarianKnight commented on content/docs/scripting-reference/runtimes/lua/functions/Citizen.InvokeNative.md
> +```lua
This doesn't seem like a very useful example imo

2024-06-05 04:24 UTC, AvarianKnight commented on content/docs/scripting-reference/runtimes/lua/functions/Citizen.InvokeNative.md
> +Citizen.InvokeNative(nativeHash, param1, param2.x, param2.y, param2.z)
This should probably be an actual example of using with a native

[SET_ENTITY_COORDS](https://docs.fivem.net/natives/?_0x06843DA7060A026B) would probably be a good native to use here

2024-06-05 04:24 UTC, AvarianKnight commented on content/docs/scripting-reference/runtimes/lua/functions/Citizen.InvokeNative.md
> +local nativeHash = 0x9ABCDEF0 -- Example hash for a variadic native
You can use [VAR_STRING](https://redm.disquse.me/natives/?_0xFA925AC00EB830B9) from RedM for this example

2024-06-05 04:26 UTC, PsychoShock commented on content/docs/scripting-manual/introduction/about-native-functions.md
> +title: Understanding and Using Native Functions in FiveM
It's only for `FiveM` - spoke to intern people about this.

2024-06-05 04:26 UTC, PsychoShock commented on content/docs/scripting-manual/introduction/about-native-functions.md
> +In FiveM, you have access to what are called "native functions" or simply "natives". These functions interact with the game directly, allowing you to perform a wide variety of actions within the game
Same comment as above

2024-06-05 04:26 UTC, PsychoShock commented on content/docs/scripting-manual/introduction/about-native-functions.md
> +FiveM provides comprehensive documentation for native functions, which can be found on our official website. This documentation is essential for understanding what each native function does, how to u
Same comment as above

2024-06-05 04:27 UTC, PsychoShock commented on content/docs/scripting-manual/introduction/about-native-functions.md
> +- **FiveM Native Reference**: The primary resource for native functions is the [FiveM Native Reference](https://docs.fivem.net/natives/). This reference includes a searchable database of all availabl
They want to include only official links to the docs even if Disquse is responsible for RedM.

2024-06-05 04:29 UTC, PsychoShock commented on content/docs/scripting-manual/introduction/about-native-functions.md
> +- **FiveM Community Forums**: The [FiveM forums](https://forum.fivem.net/) are another valuable resource. Here, you can find discussions, tutorials, and examples from other developers who share their
I agree yeah

2024-06-05 04:30 UTC, PsychoShock commented on content/docs/scripting-reference/runtimes/lua/functions/Citizen.InvokeNative.md
> +`Citizen.InvokeNative` is typically used when you need to access functionality that is not available through Lua scripting alone. This could include advanced game mechanics, low-level engine features
Related to what part?

2024-06-05 04:35 UTC, PsychoShock commented on content/docs/scripting-reference/runtimes/lua/functions/Citizen.InvokeNative.md
> +local nativeHash = 0x9ABCDEF0 -- Example hash for a variadic native
Since it's only related to FiveM - I'll keep it to FiveM only.

2024-06-05 08:59 UTC, Mathu-lmn requested changes
Good first understanding docs except a few changes that can be done to improve it !

2024-06-05 08:59 UTC, Mathu-lmn commented on content/docs/scripting-manual/introduction/about-native-functions.md
> +- **CitizenFX GitHub**: Users can contribute to the [CitizenFX GitHub repository](https://github.com/citizenfx/fivem) by adding descriptions, names, and new native functions. This collaborative effor
Maybe it would be worth including this repo too ?
https://github.com/citizenfx/natives

2024-06-05 08:59 UTC, Mathu-lmn commented on content/docs/scripting-manual/introduction/about-native-functions.md
> +## Difference Between Client Natives and Server-Side Natives
It should either be "Client-Side" and "Server-Side" or "Client" and "Server"

2024-06-05 08:59 UTC, Mathu-lmn commented on content/docs/scripting-manual/introduction/about-native-functions.md
> +### Server-Side Natives
Same here, you have to be consistent with naming, if you put "side" then do the same for client

2024-06-05 08:59 UTC, Mathu-lmn commented on content/docs/scripting-manual/introduction/about-native-functions.md
> +Server-side natives, on the other hand, run on the server. These functions manage game logic that needs to be controlled and validated by the server, such as player authentication, database interacti
Natives don't allow database interaction AFAIK ?

2024-06-05 08:59 UTC, Mathu-lmn commented on content/docs/scripting-manual/introduction/about-native-functions.md
> +- **DrawNotification**: Displays a notification on the screen.
This is not a native anymore (an old name) and I think it's not good practice to include old names in the official docs ! New name is `EndTextCommandThefeedPostTicker`.
Also this is not one of the easiest native to include in a "first understanding" docs imo. Maybe include like `GetEntityCoords` or `DeleteEntity`

2024-06-05 08:59 UTC, Mathu-lmn commented on content/docs/scripting-reference/runtimes/lua/functions/Citizen.InvokeNative.md
> +local nativeHash = 0xDCBA2512 -- This is the hash for the native function
Are you sure about the hash there ? I have `0x32CA01C3`

2024-06-05 08:59 UTC, Mathu-lmn commented on content/docs/scripting-reference/runtimes/lua/functions/Citizen.InvokeNative.md
> +`Citizen.InvokeNative` is typically used when you need to access functionality that is not available through Lua scripting alone. This could include advanced game mechanics, low-level engine features
I believe related to this part : What is Citizen.InvokeNative?

2024-06-05 14:53 UTC, PsychoShock commented on content/docs/scripting-reference/runtimes/lua/functions/Citizen.InvokeNative.md
> +local nativeHash = 0xDCBA2512 -- This is the hash for the native function
Yes good catch, thanks.

2024-06-05 23:43 UTC, TheIndra55 commented on content/docs/scripting-manual/introduction/about-native-functions.md
> +These functions are called "native" because they are built into the game engine itself. They provide a powerful interface for developers to interact with the underlying game code. Natives can perform
I'd rephrase this since natives are not only implemented in the game itself, the server also implements the natives system.

2024-06-05 23:46 UTC, AvarianKnight requested changes

2024-06-05 23:46 UTC, AvarianKnight commented on content/docs/scripting-reference/runtimes/lua/functions/Citizen.InvokeNative.md
> +local success = Citizen.InvokeNative(0x06843DA7060A026B, entityHandle, x, y, z, false, false, false, false) -- SET_ENTITY_COORDS native
The hash should be as a variable name so it documents itself

2024-06-05 23:46 UTC, AvarianKnight commented on content/docs/scripting-reference/runtimes/lua/functions/Citizen.InvokeNative.md
> +print("SetEntityCoords success:", success)
This native doesn't return anything on success/fail

2024-08-14 19:26 UTC, AvarianKnight requested changes

2024-08-14 19:26 UTC, AvarianKnight commented on content/docs/scripting-manual/introduction/about-native-functions.md
> +- **CitizenFX GitHub**: Users can contribute to the [repository](https://github.com/citizenfx/fivem) by adding descriptions, names, and new native functions. This collaborative effort helps keep the
```suggestion
- **Native Docs Repo**: Users can contribute to the [repository](https://github.com/citizenfx/natives) by adding descriptions, names, and new native functions.
```

2024-08-15 01:28 UTC, merged