feat(wait/doc): complete page
citizenfx/fivem-docs pull request #431
Opened 2024-06-05 03:28 UTC by PsychoShock

This will mostly show:
- What is Citizen.Wait
- How does it work
- Example
- Where to use it
- Tips

2024-06-07 15:58 UTC, TheIndra55 commented
In my opinion this has too much filler, while leaving out important details like that it yields "thread"/coroutine so the game can render the next frame. You should probably just extend the current page and include two examples; one example showing a 2 seconds wait, and another one explaining how/why we need the `Wait(0)` you see often in loops.

2024-06-08 20:27 UTC, PsychoShock commented
Credits to @AvarianKnight for the "Things to keep in mind" part. Thanks.

2024-08-10 04:17 UTC, AvarianKnight commented on content/docs/scripting-reference/runtimes/lua/functions/Citizen.Wait.md
> +1. **Avoid short waits**: Be cautious about using short waits in threads such as `0ms` for things that can take a higher time.
The wording here might lead people to believe that they should use `Wait(5)` and other "weird" wait times trying to "optimize" their scripts.

This should probably more so say "use different coroutines to cache values that don't need to be called every frame, and don't call expensive native calls per-frame, like [START_EXPENSIVE_SYNCHRONOUS_SHAPE_TEST_LOS_PROBE](https://docs.fivem.net/natives/?_0x377906D8A31E5586), if something needs to be run per-frame run it with `Wait(0)`."

2024-08-12 23:19 UTC, AvarianKnight requested changes

2024-08-12 23:19 UTC, AvarianKnight commented on content/docs/scripting-reference/runtimes/lua/functions/Citizen.Wait.md
> +`Citizen.Wait` is a function in FiveM that allows you to pause the execution of the current script thread for a specified amount of time. This can be useful for creating delays, scheduling tasks, or
```suggestion
`Citizen.Wait` is a function in FiveM that allows you to pause the execution of the current thread for a specified amount of time. This can be useful for creating delays, scheduling tasks, or controlling the flow of your script.
```

2024-08-12 23:19 UTC, AvarianKnight commented on content/docs/scripting-reference/runtimes/lua/functions/Citizen.Wait.md
> +## Conclusion
```suggestion

```

2024-08-12 23:19 UTC, AvarianKnight commented on content/docs/scripting-reference/runtimes/lua/functions/Citizen.Wait.md
> +`Citizen.Wait` is a simple function in FiveM scripting that allows you to control the timing and flow of your scripts. By pausing execution for a specified duration, you can create delays, schedule t
```suggestion

```

2024-08-12 23:19 UTC, AvarianKnight commented on content/docs/scripting-reference/runtimes/lua/functions/Citizen.Wait.md
> +In this example, the script will continuously print a message every 5 seconds. Note that not waiting at least `0ms` in a thread will crash the client game.
```suggestion
In this example, the script will continuously print a message every 5 seconds.

{{% alert color="warning" %}}
Doing a `while true do` loop without a `Wait` will crash the clients game, please make sure your logic doesn't accidentally prevent `Wait` from being called. 
{{% /alert %}}
```

2024-08-15 01:28 UTC, merged