feat(developpers/docs): setup guidelines
citizenfx/fivem-docs pull request #435
Opened 2024-06-06 02:53 UTC by PsychoShock

2024-06-06 05:01 UTC, 4mmonium commented on content/docs/contributing/how-you-can-help.md
> +# How You Can Help
Adding this will make the title show twice, since by default articles use the provided title given up above in this case the one at line 2.

2024-06-06 05:05 UTC, PsychoShock commented on content/docs/contributing/how-you-can-help.md
> +# How You Can Help
Ah yes, good catch. Fix.

2024-06-08 21:34 UTC, PsychoShock commented on content/docs/contributing/how-you-can-help.md
> +### Method signatures
Just also adding a method signature since it's important to keep a consistency accross all docs.

2024-08-10 03:20 UTC, AvarianKnight requested changes
Only one thing that I notice here.

2024-08-10 03:20 UTC, AvarianKnight commented on content/docs/contributing/how-you-can-help.md
> +---
```suggestion

```
I don't think this is needed for anything.

2024-08-11 14:30 UTC, merged