feat(cfx.ini/page): new doc
citizenfx/fivem-docs pull request #440
Opened 2024-06-06 18:58 UTC by PsychoShock

New page that allow user to know how to modify somehting on CitizenFX.ini

2024-06-06 19:38 UTC, PsychoShock commented on content/docs/client-manual/citizenfx.md
> +PathCL2=[Your game path]
Isn't this required when having a second FiveM instance? Or this add automatically on -cl2 shortcut?

2024-06-06 19:39 UTC, 4mmonium commented on content/docs/client-manual/citizenfx.md
> +PathCL2=[Your game path]
As tens0rfl0w says up above, this is for a secondary client path (i.e. launched using `-cl2`), it's optional and should only be used for different install paths. 

Reference [here](https://github.com/citizenfx/fivem/blob/1b01a54ea0803c8e06ef7e15bb1ae3a3d64de085/code/client/shared/Utils.Win32.cpp#L138).

2024-06-06 21:06 UTC, 4mmonium commented
I was thinking about organization and I noticed that this has no weight attribute, so I'm not sure how it will display in the navigation pane on the left. Perhaps it should be referenced as a file (with `hidden: true` attribute) within the main `_index.md` file for the client manual category, or in a different category within client-manual i.e. "Client Configuration".

Right now, this is how it would display, again I'm not sure on the positioning since no weight attribute has been set:
![image](https://github.com/citizenfx/fivem-docs/assets/38232208/597b64fe-b2ad-4a73-a488-b05f68fa1ea9)

Main issue I see is that all the items in the navigation pane follow a specific naming pattern and then there's an item being shown as a file with an extension on it.

If you want to follow the first step where you hide it from the navigation pane, ideally you would just add `hidden: true` at the top of this file and then reference this file via `client-manual/_index.md`.

Otherwise, 'Client Configuration' category with the file contents of this. I'm open to ideas. 😊

2024-06-06 22:59 UTC, PsychoShock commented
After speaking with @4mmonium, I will hide the page and add it on the `client-manual/_index.md`.

2024-06-07 03:49 UTC, AvarianKnight requested changes
I don't think the text here should be suggestive, it should mainly document what everything in the ini does.

2024-06-07 03:49 UTC, AvarianKnight commented on content/docs/client-manual/citizenfx.md
> +- Press Win+R, enter `%localappdata%\FiveM\FiveM.app\CitizenFX.ini` into the Open field, and click OK.
Should probably also remind the user that if they didn't install FiveM in their `C:/` drive it will be wherever they opened the FiveM.exe from.

2024-06-07 03:49 UTC, AvarianKnight commented on content/docs/client-manual/citizenfx.md
> +- This will open a text file in Notepad.
`in Notepad` -> `in the systems default text editor`

2024-06-07 03:49 UTC, AvarianKnight commented on content/docs/client-manual/citizenfx.md
> +This will let you enable the Geforce Experience Overlay.
For things like this it might be better to display a huge banner as there is a reason its disabled by default :)

2024-06-07 03:49 UTC, AvarianKnight commented on content/docs/client-manual/citizenfx.md
> +UpdateChannel=XXXX
This should probably have default variables instead of placeholder text

2024-06-07 03:49 UTC, AvarianKnight commented on content/docs/client-manual/citizenfx.md
> +- **production** that represent the stable version of FiveM (this does not contain latest updates)
```suggestion
- **production**: this is the stable channel for FiveM
```

2024-06-07 03:49 UTC, AvarianKnight commented on content/docs/client-manual/citizenfx.md
> +It's always important to keep the GTA V path to the right location. You are free to change to manually when you move the game path. This will tell FiveM where to get GTA V. (Please note that this is
```suggestion
This is the path to the GTA 5 installation on your local machine. You shouldn't need to modify this variable as FiveM will ask you to update the path automatically if it doesn't detect the GTA5 binary.
```

2024-06-07 03:49 UTC, AvarianKnight commented on content/docs/client-manual/citizenfx.md
> +UpdateChannel=XXXX
```suggestion
UpdateChannel=production
```

2024-06-07 03:49 UTC, AvarianKnight commented on content/docs/client-manual/citizenfx.md
> +This will let you enable the Geforce Experience Overlay.
```suggestion
**NOTE**: Enabling GeForce Experience Overlay has been known to cause crashing issues, which is why it is disabled.

This will tell FiveM to not block the GeForce Experience Overlay.
```

2024-06-07 03:49 UTC, AvarianKnight commented on content/docs/client-manual/citizenfx.md
> +EnableFullMemoryDump=1
This should have the default variable

```suggestion
EnableFullMemoryDump=0
```

2024-06-07 03:49 UTC, AvarianKnight commented on content/docs/client-manual/citizenfx.md
> +You can read more about this [here](https://forum.cfx.re/t/enabling-and-uploading-full-client-dumps/1138940). Make sure to not have disable `DisableCrashUpload`.
```suggestion
Setting this to `EnableFullMemoryDump=1` will enable Full Memory dumps which is useful for diagnosing game crashes.

These dumps are typically very large (anywhere from 1-10gb), if you have these enabled make sure to clean then out from time to time.

You can read more about this [here](https://forum.cfx.re/t/enabling-and-uploading-full-client-dumps/1138940).
```

`DisableCrashUpload` won't cause any issues here full dumps don't get uploaded as they're usually too big.

2024-06-07 03:49 UTC, AvarianKnight commented on content/docs/client-manual/citizenfx.md
> +DisableOSVersionCheck=1
```suggestion
DisableOSVersionCheck=0
```

This should be the default value

2024-06-07 03:49 UTC, AvarianKnight commented on content/docs/client-manual/citizenfx.md
> +This will disable the OS version check on Windows. Please note this may lead to issues and it's not recommanded unless you know what you are doing. You can see more [here](https://github.com/citizenf
```suggestion
By default FiveM checks if you're using using an outdated version of Windows 10 as older versions don't have certain [ABIs](https://en.wikipedia.org/wiki/Application_binary_interface) that FiveM uses.

The minimum supported version of Windows 10 is version 1703 (aka "Creators Update").

Setting this to `DisableOSVersionCheck=1` will disable the popup that happens when you start FiveM on an outdated machine.
```

2024-06-07 03:49 UTC, AvarianKnight commented on content/docs/client-manual/citizenfx.md
> +SavedBuildNumber=XXXX
```suggestion
SavedBuildNumber=1604
```

2024-06-07 03:49 UTC, AvarianKnight commented on content/docs/client-manual/citizenfx.md
> +Where `XXXX` will represent the build number you wish. You can find the list [here](docs/server-manual/server-commands/#sv_enforcegamebuild-build). This will launch FiveM app directly to the build as
```suggestion
You can find the list of game builds [here](docs/server-manual/server-commands/#sv_enforcegamebuild-build).

This will launch FiveM directly into the specified build so you don't have to transition when connecting to servers on the specified build.
```

2024-06-07 03:49 UTC, AvarianKnight commented on content/docs/client-manual/citizenfx.md
> +- **beta** that represent the "stable" version between latest updates on canary and production. This allow you to test some of the newest features.
```suggestion
- **beta**: this is the version between latest updates on canary and production which will have some of the latest features after they've been tested on canary. This version isn't guaranteed to be stable you should only use it if you're a developer or want to test new features.
```

Beta isn't "stable"

2024-06-07 03:49 UTC, AvarianKnight commented on content/docs/client-manual/citizenfx.md
> +- **canary** that represent the latest version of FiveM wich can be unstable. This is not recommanded unless you know what you are doing.
```suggestion
- **canary**: this channel will have the latest build of FiveM. This channel is unstable, **do not use this build unless you're fine with issues, crashes, etc.**.

2024-06-07 03:49 UTC, AvarianKnight commented on content/docs/client-manual/citizenfx.md
> +You can replace `XXXX` by:
```suggestion
UpdateChannel can have the following values:
```

2024-06-07 03:49 UTC, AvarianKnight commented on content/docs/client-manual/citizenfx.md
> +DisableCrashUpload=1
```suggestion
DisableCrashUpload=0
```

2024-06-07 03:49 UTC, AvarianKnight commented on content/docs/client-manual/citizenfx.md
> +This will disable the crash metrics upload automatically on FiveM path. You can see more [here](https://github.com/citizenfx/fivem/blob/1b01a54ea0803c8e06ef7e15bb1ae3a3d64de085/code/client/launcher/M
```suggestion
Setting this to `DisableCrashUpload=1` will disable the game from automatically uploading the crash dumps to the Cfx Sentry.
```

2024-06-07 03:51 UTC, PsychoShock commented on content/docs/client-manual/citizenfx.md
> +Please note that this file shouldn't be modified if you don't know what you are doing. For any issue join our [discord](discord.gg/fivem).
Yeah I agree

2024-06-07 03:53 UTC, PsychoShock commented on content/docs/client-manual/citizenfx.md
> +- Press Win+R, enter `%localappdata%\FiveM\FiveM.app\CitizenFX.ini` into the Open field, and click OK.
Yeah forgot to add that part, good catch.

2024-06-07 03:55 UTC, PsychoShock commented on content/docs/client-manual/citizenfx.md
> +This will let you enable the Geforce Experience Overlay.
A warning banner? Like a "enabling this might cause some game performance issue"?

2024-06-07 03:55 UTC, PsychoShock commented on content/docs/client-manual/citizenfx.md
> +UpdateChannel=XXXX
Hmm I'll let @4mmonium decide for that, while I agree, I think explaining from placeholder is easier.

2024-06-07 03:57 UTC, PsychoShock commented on content/docs/client-manual/citizenfx.md
> +UpdateChannel=XXXX
Reference to https://github.com/citizenfx/fivem-docs/pull/440#discussion_r1630613913

2024-06-07 03:58 UTC, PsychoShock commented on content/docs/client-manual/citizenfx.md
> +This will let you enable the Geforce Experience Overlay.
If following https://github.com/citizenfx/fivem-docs/pull/440#discussion_r1630613619, I'll do a special warning for this.

2024-06-07 03:59 UTC, PsychoShock commented on content/docs/client-manual/citizenfx.md
> +EnableFullMemoryDump=1
I mean the option is mainly to active it so easier for the user to copy directly. Regular user wouldn't have that at first.

2024-06-07 04:01 UTC, PsychoShock commented on content/docs/client-manual/citizenfx.md
> +You can read more about this [here](https://forum.cfx.re/t/enabling-and-uploading-full-client-dumps/1138940). Make sure to not have disable `DisableCrashUpload`.
Yes right, didn't saw https://github.com/citizenfx/fivem/blob/1b01a54ea0803c8e06ef7e15bb1ae3a3d64de085/code/client/launcher/MiniDump.cpp#L1649C26-L1649C41. Good catch.

2024-06-07 04:01 UTC, PsychoShock commented on content/docs/client-manual/citizenfx.md
> +DisableOSVersionCheck=1
Reference https://github.com/citizenfx/fivem-docs/pull/440#discussion_r1630617302

2024-06-07 04:05 UTC, AvarianKnight commented on content/docs/client-manual/citizenfx.md
> +UpdateChannel=XXXX
I don't agree with this, I think providing the default value for each ini variable makes more sense as it shows how it is actually used, users should be able to infer based off of the information provided.

In places that you can't (like ones that are basically bools) you provide an explanation for how to change it (like how I did here: https://github.com/citizenfx/fivem-docs/pull/440/files#r1630585240)

2024-06-07 04:07 UTC, PsychoShock commented on content/docs/client-manual/citizenfx.md
> +UpdateChannel=XXXX
I'll replace with latest versions of everything then.

2024-08-10 04:30 UTC, AvarianKnight commented
My previous points here still stand, these should have their values set to their default where possible.

2024-08-11 14:28 UTC, merged