feat(shortcut/page): new doc
citizenfx/fivem-docs pull request #442
Opened 2024-06-06 23:47 UTC by PsychoShock

This will make user know how to launch FiveM with specific settings. This page is hidden by default and can only be found by direct link or index page of client-manual.

2024-08-12 23:03 UTC, AvarianKnight commented
Can you rebase this

2024-08-13 00:20 UTC, PsychoShock commented
I was also thinking switching the XXX to real values. What do you think?

2024-08-15 19:03 UTC, AvarianKnight requested changes

2024-08-15 19:03 UTC, AvarianKnight commented on content/docs/client-manual/shortcut.md
> +   - Navigate to the FiveM installation directory, **typically** found at `C:\Users\[YourUsername]\AppData\Local\FiveM`.
```suggestion
   - Navigate to the FiveM installation directory, **typically** found at `%localappdata%\FiveM`.
```

2024-08-15 19:05 UTC, merged