feat(game-refs/vehicle-models): now using html to draw vehicle models
citizenfx/fivem-docs pull request #447
Opened 2024-06-08 02:05 UTC by ahcenezdh

Instead of using a markdown table, we are now using HTML/CSS to display every vehicle model

![image](https://github.com/citizenfx/fivem-docs/assets/40030799/73e6791b-5b42-426d-9e7a-56264105fd76)

All vehicles are sorted by their categories.
![image](https://github.com/citizenfx/fivem-docs/assets/40030799/5f9b8e45-25a8-43be-bc50-81b2e08b494e)

⚠️ Known problem
Some vehicle cards are smaller or bigger than others. If someone has a fix, I'm open to suggestions.
Some vehicles don't have images:

```
astron custom
arbitergt
cyclone2
ignus2
everon
```

All vehicles data were generated with a nodeJS script using this <a href="https://github.com/DurtyFree/gta-v-data-dumps/blob/master/vehicles.json">list</a>

I sent a message to @fengorian and am waiting for his feedback.

2024-06-08 02:06 UTC, ahcenezdh commented
If you want to build the docs, see #417

2024-06-08 02:25 UTC, AvarianKnight commented
Why not keep the `height` property as I assume it will fix the 

> Some vehicle cards are smaller or bigger than others. If someone has a fix, I'm open to suggestions

2024-06-08 12:02 UTC, ahcenezdh commented
> Why not keep the `height` property on the img, as I assume it will fix the
> 
> > Some vehicle cards are smaller or bigger than others. If someone has a fix, I'm open to suggestions

Should be good

2024-06-09 21:48 UTC, PsychoShock commented
While reworking the page, adding vehicles supported in each builds could be a nice feature. That way, announcements could refer to this doc page on release.

2024-06-11 13:52 UTC, ahcenezdh commented
> While reworking the page, adding vehicles supported in each builds could be a nice feature. That way, announcements could refer to this doc page on release.

I don't know for this, @4mmonium is it ok for you?

2024-08-10 18:56 UTC, AvarianKnight requested changes

2024-08-10 18:56 UTC, AvarianKnight commented on content/docs/game-references/vehicle-models.md
> +        grid-template-columns: repeat(auto-fill, minmax(180px, 1fr));
```suggestion
        grid-template-columns: repeat(4, 180px);
```
Workaround for hover css in the docs causing the auto-fill to only show one car per line on hover

2024-08-10 18:56 UTC, AvarianKnight commented on content/docs/game-references/vehicle-models.md
> +        justify-content: center;
```suggestion

```
Workaround for the front-end trying to fit content on hover of the first item causing the layout to shift to the left constantly.

2024-08-11 03:45 UTC, AvarianKnight commented
Pushed a change to use markdown headers instead of h2's so we don't need the extra table of contents at the top

![image](https://github.com/user-attachments/assets/fea4a840-9999-460a-b880-78cc18b7cc12)

2024-08-11 04:11 UTC, AvarianKnight commented
There's currently a few vehicles missing images

- astron2
- arbitergt
- cyclone2
- ignus2
- everon

2024-08-11 17:40 UTC, ahcenezdh commented
> There's currently a few vehicles missing images
> 
> * astron2
> * arbitergt
> * cyclone2
> * ignus2
> * everon

For vehicles images, you have to see with @fengorian since those images were made by him

2024-08-12 23:25 UTC, merged