feat(doc): add security guideline
citizenfx/fivem-docs pull request #457
Opened 2024-07-09 21:08 UTC by PsychoShock

This will be a good "start" for people building security in their server.

2024-07-10 16:09 UTC, Mathu-lmn requested changes
Good start overall :)

2024-07-10 16:09 UTC, Mathu-lmn commented on content/docs/developers/server-security.md
> +User getting kick doesn't mean is automatically Global Ban. However, it provides an indication of player reliability, which can be useful for assessing trustworthiness.
User getting kick**ed** doesn't mean **he** is automatically globally banned

2024-07-10 16:09 UTC, Mathu-lmn commented on content/docs/developers/server-security.md
> +The codes provided are not suppose to be working on a copy/paste method. This is just some tips to prevent some actions that might happen in the server. This require some knowledge, you are always fr
suppose**d**

2024-07-10 16:09 UTC, Mathu-lmn commented on content/docs/developers/server-security.md
> +Some cheats authorize the client to trigger events allowing them to have access to a wide possibilities, let's see how you can protect them:
Could be interesting mentioning event honeypots too

2024-07-10 16:09 UTC, Mathu-lmn commented on content/docs/developers/server-security.md
> +Make sure to retrieve all values using server-side methods, not allowing players to change the values. This ensures the integrity and security of your game environment. Please note that client checks
overridden instead of ovverided

2024-07-10 16:09 UTC, Mathu-lmn commented on content/docs/developers/server-security.md
> +Even thought we are trying to keep our community safe, some users might have not been detected yet. This is some tools to prevents some popular actions:
though not thought :p
`There are some tools to prevent` instead of `This is some tools to prevents`

2024-08-09 20:04 UTC, AvarianKnight commented
I don't think that resource specific exploitation/mitigations should be included in the fivem docs.

Some of this would probably be better off living in a modding tutorial and be linked to from this doc.

@PsychoShock thoughts?

2024-08-09 20:12 UTC, PsychoShock commented
> I don't think that resource specific exploitation/mitigations should be included in the fivem docs.
> 
> Some of this would probably be better off living in a modding tutorial and be linked to from this doc.
> 
> @PsychoShock thoughts?

I had the same thought—although the resource is extremely popular, this document is more about *demonstrating* how to prevent general situations rather than focusing on this specific resource. While I agree that a modding tutorial linked to the main docs could work, it would lead users to multiple documents (unless you have a better option). Perhaps I could remove the specific examples and keep the guidance more general?

Do you have anything in mind?

2024-08-09 20:20 UTC, AvarianKnight commented
> While I agree that a modding tutorial linked to the main docs could work, it would lead users to multiple documents (unless you have a better option). Perhaps I could remove the specific examples and keep the guidance more general?

I think this is a good idea, just remove the resource specific example

2024-08-09 20:35 UTC, PsychoShock commented
> > While I agree that a modding tutorial linked to the main docs could work, it would lead users to multiple documents (unless you have a better option). Perhaps I could remove the specific examples and keep the guidance more general?
> 
> I think this is a good idea, just remove the resource specific example

These examples are retained because they are helpful for understanding, but I also added a note that they do not represent any specific resources.

2024-08-10 04:28 UTC, AvarianKnight commented
The issue here is that SQL related attacks are not related to FiveM at all.

2024-08-10 05:51 UTC, PsychoShock commented
So we just remove all the SQL section? I just added since it's something "good" for people to know. Up to you--feel free to remove what ever part you wish and merge the rest if it simplier. I'll stay available if any change.

2024-08-12 23:09 UTC, AvarianKnight reviewed
Some suggestions based on previous conversation

2024-08-15 19:02 UTC, merged