Update Server/Client issues section
citizenfx/fivem-docs pull request #468
Opened 2024-08-10 09:30 UTC by colistro123

This pull request removes outdated articles from the documentation that are now available in the Cfx.re support section. It also directs users to these articles under the "Help! I can't find my issue here!" header. 

Additionally, it updates certain articles in the server issues section, correcting outdated information such as the server capacity limit, which has increased from 32 to 48 slots on OneSync (up to 2048 of course), now provided by default. It also directs users to the relevant support article instructing them how to link their keymaster account to Patreon.

This will most likely require team approval 😊

2024-08-10 19:37 UTC, colistro123 commented
Re-added changes from @PsychoShock and pushed using rebase strategy.

2024-08-10 20:29 UTC, colistro123 commented
For client issues, I realized that removing these sections entirely may not have been the best approach. Instead, I linked to the relevant support sections to reduce clutter on the page while still providing access to important information.

2024-08-11 04:19 UTC, AvarianKnight requested changes

2024-08-11 04:19 UTC, AvarianKnight commented on content/docs/support/server-issues.md
> +1. Use a license key with Premium access
```suggestion
1. Use a license key with OneSync access
```
Probably better to not change this wording.

2024-08-11 06:26 UTC, colistro123 commented on content/docs/support/server-issues.md
> +1. Use a license key with Premium access
> Probably better to not change this wording.

Sure! 😊

2024-08-15 14:32 UTC, merged