feat(game-refs/veh-refs): add vehicle-references and vehicle flags
citizenfx/fivem-docs pull request #480
Opened 2024-09-08 16:20 UTC by ahcenezdh

* Moved vehicles data into the vehicle-references section
* Added a vehicle flags page

Related to https://github.com/citizenfx/fivem/pull/2747
Was tested by building the docs

2024-09-15 04:08 UTC, AvarianKnight requested changes

2024-09-15 04:08 UTC, AvarianKnight commented on content/docs/game-references/vehicle-references/_index.md
> +weight: 700
```suggestion
weight: 740
```
This shouldn't be before controls.

2024-09-15 04:08 UTC, AvarianKnight commented on content/docs/game-references/vehicle-references/vehicle-flags.md
> +<div class="flags">
Why not use a markdown table here?

2024-09-18 19:43 UTC, PsychoShock requested changes

2024-09-18 19:43 UTC, PsychoShock commented on content/docs/game-references/vehicle-references/_index.md
> +- [Vehicle colours](/docs/game-references/vehicle-references/vehicle-colours)
```suggestion
- [Vehicle colors](/docs/game-references/vehicle-references/vehicle-colors)
```

Docs use AmE so you need to remove `u` from `colours`. Don't forget to change the page file too.

2024-09-29 11:22 UTC, ahcenezdh commented
@AvarianKnight should be good

2024-10-10 14:47 UTC, AvarianKnight commented on content/docs/game-references/input-mapper-parameter-ids/_index.md
> +---
Why does this file have any changes?

2024-10-11 19:33 UTC, ahcenezdh commented on content/docs/game-references/input-mapper-parameter-ids/_index.md
> +---
Probably my vscode

2024-10-11 19:34 UTC, ahcenezdh commented on content/docs/game-references/input-mapper-parameter-ids/_index.md
> +---
(Yes those are whitespaces it's my vscode who's messing with whitespaces)

2024-10-15 17:57 UTC, AvarianKnight commented on content/docs/game-references/input-mapper-parameter-ids/_index.md
> +---
Can you remove the changes and then force push?

2024-10-15 20:34 UTC, ahcenezdh commented on content/docs/game-references/input-mapper-parameter-ids/_index.md
> +---
Should be good

2024-12-02 17:45 UTC, AvarianKnight commented
Looks good to me, thanks!

2024-12-02 18:13 UTC, AvarianKnight approved these changes

2024-12-02 18:15 UTC, merged