docs(game/five): documentation for sv_replaceExeToSwitchBuilds flag
citizenfx/fivem-docs pull request #493
Opened 2024-10-28 11:15 UTC by Nobelium-cfx

The flag was introduced in
https://github.com/citizenfx/fivem/commit/df68640468051893a722a96aff90cb35412c186d

2024-10-28 12:56 UTC, prikolium-cfx approved these changes

2024-10-31 01:34 UTC, AvarianKnight requested changes

2024-10-31 01:34 UTC, AvarianKnight commented on content/docs/server-manual/server-commands.md
> +NOTE: The difference in `sv_replaceExeToSwitchBuilds` should be **invisible** to players and server owners. If you notice a disparity please report it as a bug.
```suggestion
NOTE: The difference in `sv_replaceExeToSwitchBuilds` should be **invisible** to players and server owners. If you notice a disparity please [report it as a bug](https://github.com/citizenfx/fivem/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=bug_report.yml).
```

2024-10-31 01:34 UTC, AvarianKnight commented on content/docs/server-manual/server-commands.md
> +    If `sv_enforceGameBuild = 1` - the client will run as if `sv_replaceExeToSwitchBuilds = false` regardless of which value is set. That's the only way how base game without DLCs behavior can be ach
```suggestion
    If `set sv_enforceGameBuild 1` - the client will run as if `sv_replaceExeToSwitchBuilds = false` regardless of which value is set. That's the only way how base game without DLCs behavior can be achieved.
```

2024-10-31 01:34 UTC, AvarianKnight commented on content/docs/server-manual/server-commands.md
> +- true: the default value. Corresponds to the default behavior before this variable was introduced. The client will load executable and all the files corresponding to the enforced game build.
```suggestion
- true: the default value. This will keep the current client behavior, the client will download all the files for the specific game build and have to restart their client to join servers.
```

I'm not entirely sure how this works, you should remove the "and have to restart their client to join servers." if this is still required for the new system

2024-10-31 01:34 UTC, AvarianKnight commented on content/docs/server-manual/server-commands.md
> +- false: The client will run executable for one of the latest game builds, regardless of which game build is enforced. Instead the set of content will be changed to correspond to the enforced game bu
```suggestion
- false: The client will run executable for the latest game builds, regardless of which game build is enforced. Instead the client will only load the specific DLCs related to the game build specified in `sv_enforceGameBuild`. From the user perspective the game will look the same way as under `sv_replaceExeToSwitchBuilds = true`.
```

2024-10-31 09:40 UTC, Nobelium-cfx commented on content/docs/server-manual/server-commands.md
> +- true: the default value. Corresponds to the default behavior before this variable was introduced. The client will load executable and all the files corresponding to the enforced game build.
Unfortunately reloads are still required.

2024-10-31 09:42 UTC, Nobelium-cfx commented
@AvarianKnight thanks for the suggestions. Applied them now. PTAL.

2024-11-01 14:52 UTC, AvarianKnight commented on content/docs/server-manual/server-commands.md
> +    If set `sv_enforceGameBuild 1` - the client will run as if `sv_replaceExeToSwitchBuilds = false` regardless of which value is set. That's the only way how base game without DLCs behavior can be a
```suggestion
    When using `set sv_enforceGameBuild 1` the client will run as if `sv_replaceExeToSwitchBuilds = false` regardless of if it was set to `true` before. That's the only way how base game without DLCs behavior can be achieved.
```

Let me know if you agree with the wording here, it felt a bit hard to figure out what `which value is set` is referring to with context clues

2024-11-01 15:22 UTC, Nobelium-cfx commented on content/docs/server-manual/server-commands.md
> +    If set `sv_enforceGameBuild 1` - the client will run as if `sv_replaceExeToSwitchBuilds = false` regardless of which value is set. That's the only way how base game without DLCs behavior can be a
Suggested wording looks good. Applied. Thank you for the help! ^^

2024-11-01 15:24 UTC, AvarianKnight approved these changes
LGTM 😄

2024-11-01 15:25 UTC, merged