docs(developers/server-security): fix typo in server-security.md
citizenfx/fivem-docs pull request #498
Opened 2024-11-05 15:23 UTC by mardev-xyz

2024-11-06 00:01 UTC, colistro123 requested changes
Hey there, suggested a change.

2024-11-06 00:03 UTC, PsychoShock commented
Ah oops, me and my bad English grammar 🙈

2024-11-06 13:02 UTC, mardev-xyz commented
> Hey there, suggested a change.

Added the suggestion :)

2024-11-07 05:16 UTC, AvarianKnight requested changes

2024-11-07 05:16 UTC, AvarianKnight commented on content/docs/developers/server-security.md
> +Kicking a user does not necessarily lead to a Global Ban. However, it provides an indication of player reliability, which can be useful for assessing trustworthiness.
```suggestion
The player getting kicked does not necessarily mean a malicious player.
```
We're better off not leading people to believe that these are 100% accurate currently.

2024-11-07 07:16 UTC, mardev-xyz commented
Added requested changes, once again!

2024-11-07 07:17 UTC, mardev-xyz commented
@AvarianKnight Your change has been added aswell!

2024-11-10 22:44 UTC, AvarianKnight commented
This will be superseded by https://github.com/citizenfx/fivem-docs/pull/501

2024-11-11 00:34 UTC, colistro123 commented on content/docs/developers/server-security.md
> +The player getting kicked does not necessarily mean a malicious player.
I will implement this change in the other PR and will credit this PR for it 😀

2024-12-02 18:23 UTC, closed without merging