feat: include oal in resource manifest
citizenfx/fivem-docs pull request #502
Opened 2024-11-15 10:40 UTC by Z3rio

Hello, I've noticed that there's genuinely no clear information on OAL in the documentation

I do understand that this might be an experimental feature, but a lot of people want to understand it and start to play around with it.
A good start would be to add it to the resource manifest docs, but with a disclaimer.

2024-11-18 18:26 UTC, Z3rio commented
@AvarianKnight Does this look better? 🚀

2024-12-02 17:58 UTC, AvarianKnight requested changes

2024-12-02 17:58 UTC, AvarianKnight commented on content/docs/scripting-reference/resource-manifest/resource-manifest.md
> +This feature is still experimental and also **requires** [Lua 5.4](#lua54) to be used.
```suggestion
This feature is still experimental and **requires** [Lua 5.4](#lua54) to be used.
```

2024-12-02 17:58 UTC, AvarianKnight commented on content/docs/scripting-reference/resource-manifest/resource-manifest.md
> +Vector unpacking is not a feature when using OAL, this means that you will have to explicitly unpack each coordinate into the native. Example below.
```suggestion
Vector unpacking does not work when using OAL, this means that you will have to manually unpack coordinates instead of providing the `vector3`.
```

2024-12-02 17:58 UTC, AvarianKnight commented on content/docs/scripting-reference/resource-manifest/resource-manifest.md
> +Therefore, please ensure the types of the native parameters if you want to use OAL.
```suggestion
OALs main downside is that it cannot be used if the parameter type is wrong, as internally it will be converted to whatever the underlying type is.

This means that for natives that are undocumented or don't have the right types OAL will break in unexpected ways, or likely just not working at all.
```

2024-12-18 20:17 UTC, AvarianKnight commented
LGTM, Thanks 😃

2024-12-18 20:17 UTC, merged