docs(server/commands): add documentation about debugging pool sizes
citizenfx/fivem-docs pull request #507
Opened 2024-11-21 13:30 UTC by Nobelium-cfx

Documentation for changes in pool size limits validation made in https://github.com/citizenfx/fivem/commit/7dbd3d331e7970551b852513c428a13cea98991e

2024-11-21 18:10 UTC, colistro123 commented on content/docs/server-manual/server-commands.md
> +It is possible to bypass the pool size limitations for development purposes. In this case the pool size validation will be skipped. In order to do so you need to set `moo` [convar](https://docs.fivem
Nitpick, but may I suggest:

```suggestion
It is possible to bypass the pool size limitations for development purposes. In this case the pool size validation will be skipped. In order to do so you need to set `moo` [convar](/docs/scripting-reference/convars/#standard-convars) to `31337` independently on server and client side:
```

It's better not to use URLs; that way documentation won't be affected if the subdomain ever changes.

2024-11-21 18:12 UTC, colistro123 commented on content/docs/server-manual/server-commands.md
> +- Add `+set moo 31337` flag when running your client. Similarly to how it's done to turn on [the developer mode](https://docs.fivem.net/docs/client-manual/console-commands/#developer-commands).
Just nitpicking really 😊

```suggestion
- Add `+set moo 31337` flag when running your client. Similarly to how it's done to turn on [the developer mode](/docs/client-manual/console-commands/#developer-commands).
```

2024-11-21 18:36 UTC, colistro123 reviewed
Left some minor feedback regarding links. I thought might be helpful to avoid using `https://` URLs or subdomains in documentation to keep things consistent. Just obsessing over the small details 😅

2024-12-02 17:41 UTC, AvarianKnight requested changes

2024-12-02 17:41 UTC, AvarianKnight commented on content/docs/server-manual/server-commands.md
> +NOTE: This is for development and debugging purposes only. Never use it to bypass limitations for your production environment. If you set pool sizes outside of supported limits - you are on your own.
```suggestion
{{% alert color="warning" %}}
This is for development and debugging purposes only. Never use it to bypass limitations for your production environment. If you set pool sizes outside of supported limits - you are on your own. If you believe that the limits should be adjusted - reach out to Cfx team for support instead.
{{% /alert %}}
```

This will hopefully catch peoples attentions to read this. Also changes CFX -> Cfx

2024-12-02 18:10 UTC, AvarianKnight approved these changes

2024-12-18 20:16 UTC, merged