tweak(scripting/listening-for-events): Source - mention asynchronous
citizenfx/fivem-docs pull request #508
Opened 2024-11-27 11:58 UTC by PulseHarbor

Add usage about `source`, since its affected during an asynchronous thread.
Happens in Lua; This probably happens with JS as-well, based on JS thread knowledge.

2024-11-29 16:05 UTC, colistro123 commented on content/docs/scripting-manual/working-with-events/listening-for-events.md
> +In Lua/JS, the `source` variable (global) will contain the player ID that triggered the event. You should most likely save it in a local variable if you're going to use it after the event returns or
What is meant by asynchronous functionality here? Does it mean that the event is classified as a `Task` in `C#`, that it uses a `coroutine` in `lua` i.e. `Citizen.CreateThread`? I believe it needs to be a little bit more explicit and explain as on to what exactly is meant by this, as in what scenarios would actually cause this to happen when directly dealing with `source`.

2024-12-02 18:22 UTC, AvarianKnight requested changes

2024-12-02 18:22 UTC, AvarianKnight commented on content/docs/scripting-manual/working-with-events/listening-for-events.md
> +In Lua/JS, the `source` variable (global) will contain the player ID that triggered the event. You should most likely save it in a local variable if you're going to use it after the event returns or
```suggestion
In Lua/JS, the `source` variable (global) will contain the player ID that triggered the event. You must save the source to a local variable if you plan on using it after the event returns, or inside of an asynchronous scope, as the source is only guaranteed to be valid for the initial event call. Calling `Wait` in Lua or awaiting something in JS will cause the global source to be set back to default.
```

This should probably provide enough context on why you should do this

2024-12-18 20:15 UTC, AvarianKnight commented
LGTM, Thank you :)

2024-12-18 20:16 UTC, merged